### ISSUE TITLE
Need optional keywords to be selectable by the user

### ISSUE THREAD

**Issue by psbanka** [ciena-frost/ember-frost-date-picker#16]
There are use-cases for the date/time picker when the user needs to be able to specify a specific keyword rather than a date/time. For example, there are user-cases when we are asking a user when something should happen. Sometimes an appropriate answer to this is "Now" or "Never". The date-time widget should support that as an option.

**Comment by job13er** [comment]
Just clarifying. What's being requested is for the component to accept a set of possible string values and allow the user to choose one of those instead of a date? So, kinda like combining a `frost-select` with the `frost-date-picker`?

Are we sure that functionality belongs in this component? It feels like a date picker should pick, well, a date ;) I could see a short-cut for `Today` or `Now` that picks the current date, but I wouldn't expect it to return the string "Today". 

If it's a common enough use-case, maybe a custom renderer that ships with `ember-frost-bunsen`? I'm certainly open to being convinced it belongs here though.

**Comment by dafortin** [comment]
I agree with @job13er. I think that a custom renderer is a very good idea.

**Comment by sglanzer** [comment]
I've had some discussion around including a range component within this repo as a partner component, I think that might be the appropriate home for this (although "Now" is probably useful in all cases)

**Comment by sglanzer** [comment]
Customizable output display - e.g.

```
{label: 'Now', value: 'now'}
```
or
```
{label: 'Now', value: moment()}
```
