### ISSUE TITLE
HTTP 502 error when running bower install

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-date-picker#99]
# BUG REPORT

* [x] I have ensured that the issue isn't already reported
* [x] I have confirmed that the issue is reproducible with the latest released version
* [x] I have deleted the **FEATURE REQUEST / CODE CHANGE** section

## Summary
* Error when running `bower install`

## Expected Behavior
* Should not throw an error when running `bower install`

## Actual Behavior
* Error `EINVRES Request to https://bower.herokuapp.com/packages/font-awesome failed with 502` appears in the console when running `bower install`

## Possible Solution
* Include a `registry` entry in the `.bowerrc` file to point to the new bower.io domain

## Steps to Reproduce
* Clone the repository
* run `npm install`
* run `bower install`

## Environment

(answer all that are applicable)

* [x] I am using the latest released version (can check with `npm ls <package-name>`)
* I am using these browsers:
  * [ ] Latest Chrome
  * [ ] Latest Firefox
* [x] My version of `Node` is: 10.5.0
* [x] My version of `npm` is: 6.1.0
* [x] My OS is: macOS High Sierra (10.13.5)
* [ ] Include the contents of your _package.json_ file

**Comment by notmessenger** [comment]
@jscharf What is your version of Bower?  I am running 1.8.4 and when I tried to replicate this issue I cannot.

```
[jerbrown@USMR-JERBROWN-1 throwaway]$ git clone git@github.com:ciena-frost/ember-frost-date-picker.git
Cloning into 'ember-frost-date-picker'...
remote: Counting objects: 2484, done.
remote: Total 2484 (delta 0), reused 0 (delta 0), pack-reused 2484
Receiving objects: 100% (2484/2484), 6.57 MiB | 2.60 MiB/s, done.
Resolving deltas: 100% (1328/1328), done.
[jerbrown@USMR-JERBROWN-1 throwaway]$ cd ember-frost-date-picker/
[jerbrown@USMR-JERBROWN-1 ember-frost-date-picker (master)]$ npm install

> node-sass@4.9.0 install /Users/jerbrown/Desktop/throwaway/ember-frost-date-picker/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-64_binding.node
Download complete
Binary saved to /Users/jerbrown/Desktop/throwaway/ember-frost-date-picker/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/jerbrown/.npm/node-sass/4.9.0/darwin-x64-64_binding.node

> spawn-sync@1.0.15 postinstall /Users/jerbrown/Desktop/throwaway/ember-frost-date-picker/node_modules/spawn-sync
> node postinstall


> node-sass@4.9.0 postinstall /Users/jerbrown/Desktop/throwaway/ember-frost-date-picker/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/jerbrown/Desktop/throwaway/ember-frost-date-picker/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
added 1891 packages from 1830 contributors and audited 102661 packages in 83.613s
found 249 vulnerabilities (139 low, 40 moderate, 69 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[jerbrown@USMR-JERBROWN-1 ember-frost-date-picker (master)]$ bower install
bower font-awesome#^4.6.3       cached https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower font-awesome#^4.6.3     validate 4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#^4.6.3
bower font-awesome#^4.6.3      install font-awesome#4.7.0

font-awesome#4.7.0 bower_components/font-awesome
[jerbrown@USMR-JERBROWN-1 ember-frost-date-picker (master)]$
```

**Comment by notmessenger** [comment]
My initial reaction is that there is value because it keeps developers from running into this situation.  However I do not believe we should add it and there are several basically-related reasons why.

If between version 1.8.0 and 1.8.4 the Bower registry url changed and an update to Bower was made to accommodate it what is to keep the same situation from occurring again in the future?  We will have entered a value for the registry today that could become incorrect again tomorrow, whereas if a developer kept their tooling up to date then we have not introduced a brittle connection point between the two.

If this scenario is occurring in this repository then it is also occurring in all the other repositories so shouldn't we make the same change there as well?  Except we really don't want to do that 75+ times.  And the fact that we know we don't speaks to the fact that we know it's because we shouldn't be doing it.

And this is only needed "for you".  Others using an updated version of Bower will not experience this.  Yes, this ties back into my very first sentence of how it keeps devs from experiencing this but where do we stop incorporating the changes/features provided/addressed by our tools in new versions of them instead of just upgrading?  Taken to an absolute ridiculous extreme for the sake of this conversation you could end up with a lot of changes in our repos just to "avoid" upgrading (not saying that it is what you are doing at all).

**Comment by jscharf** [comment]
I have re-tested this with Bower 1.8.4 and did not see the issue. I agree with your sentiment that it would be unfortunate to have to update the `.bowerrc` file for every repository in our ecosystem. Knowing now that this issue is fixed with a new version of Bower, I will close this issue. 

I also found out how I stumbled on this issue. `ember-frost-date-picker` lists Bower as a dependency in its `package.json` file. I verified that version had been updated to version 1.8.4 and then ran bower install, and still saw the 502 error. BUT, my global Bower version was still 1.8.0, which is what was being used when I ran `bower install`.
